kafka:
  bootstrap_servers: "xxxxxx.kafka-serverless.us-east-1.amazonaws.com:9098"
  topic: "user"              # Kafka topic name
  cluster_name: "StreamingGovernanceStack"  # Kafka cluster name
  client_id: "example-client"            # Kafka client ID
  authentication: "iam"                  # Options: "unauthenticated", "sasl/scram", "iam"
  group_id: "openlineage-consumer-group" # Kafka consumer group ID (this will also be the job name in OpenLineage)
  auto_offset_reset: "earliest"            # Offset reset: 'earliest' or 'latest'

gsr:
  registry_name: "governance-msk-registry"      # Glue Schema Registry name
  schema_file: "user.avsc"               # Schema file (if applicable)
  region: "us-east-1"                    # AWS region for Glue Schema Registry

openlineage:
  transport_type: "datazone"             # Transport type for OpenLineage: e.g., 'datazone', 'print'
  domain_id: "dzd_xxxxxx"        # DataZone domain ID
  region: "us-east-1"